- name: create workspace
  file: path={{ workspace }} state=directory

- name: deploy core addons
  include: deploy.yml
  with_items:
  - kube-system.yml
  - dns.yml
  - kube-datadog.yml
  - dashboard.yml

- name: deploy datadog-agent
  include: deploy.yml
  when: datadog_statsd_host == "127.0.0.1:8125"
  with_items:
  - datadog.yml

- name: deploy signalfx
  include: deploy.yml
  when: signalfx_enabled
  with_items:
  - signalfx.yml

- name: clean up workspace
  file: path={{ item }} state=absent
  with_fileglob:
  - "{{ workspace }}/*"
